Launcher3: Add null check for BaseDragLayer
@neobuddy89: Squash separate fixes.

Fixes:

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getScrollX()' on a null object reference
	at com.android.launcher3.Utilities.mapCoordInSelfToDescendant(Utilities.java:335)
	at com.android.launcher3.Workspace.updateIsBeingDraggedOnTouchDown(Workspace.java:1236)
	at com.android.launcher3.PagedView.onInterceptTouchEvent(PagedView.java:1081)
	at com.android.launcher3.Workspace.onInterceptTouchEvent(Workspace.java:1168)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2652)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:303)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:225)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:535)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1925)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4298)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:2189)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:493)
	at android.view.View.dispatchPointerEvent(View.java:14884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6396)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5874)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5897)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6062)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5905)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6119)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5897)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5905)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8891)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8807)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8776)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9027)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loopOnce(Looper.java:182)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

Change-Id: I2dab889e416aae07a9a4b9d9b7328e5f594d1154
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
(cherry picked from commit 8d7b87def4f04178bdbbc3b8a1c40acb6161d545)
Signed-off-by: Jis G Jacob <studiokeys@blissroms.org>