Launcher3: QuickstepAtomicAnimationFactory: Add some null checks to prevent NPEs
Solves the following crash on exiting recents when nothing is on any
home screen:
FATAL EXCEPTION: main
Process: com.android.launcher3, PID: 7671
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getVisibility()' on a null object reference
	at com.android.launcher3.uioverrides.states.QuickstepAtomicAnimationFactory.prepareForAtomicAnimation(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:303)
	at com.android.launcher3.statemanager.StateManager.goToStateAnimated(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:26)
	at com.android.launcher3.statemanager.StateManager.goToState(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:23)
	at com.android.launcher3.statemanager.StateManager.goToState(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:2)
	at com.android.quickstep.views.LauncherRecentsView.handleStartHome(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:16)
	at com.android.quickstep.views.RecentsView.startHome(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:3)
	at com.android.quickstep.views.RecentsView.startHome(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:1)
	at com.android.quickstep.views.RecentsView$21.onEnd(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:394)
	at com.android.quickstep.views.RecentsView$21.accept(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:4)
	at com.android.quickstep.views.RecentsView$21.accept(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:1)
	at com.android.launcher3.anim.AnimatorListeners$EndStateCallbackWrapper.onAnimationEnd(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:32)
	at com.android.launcher3.anim.AnimatorPlaybackController$$ExternalSyntheticLambda0.accept(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:14)
	at com.android.launcher3.anim.AnimatorPlaybackController.$r8$lambda$bF6fu10ogo158poE8C5B_R0HpFg(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:27)
	at com.android.launcher3.anim.AnimatorPlaybackController$$ExternalSyntheticLambda3.accept(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:12)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:1)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:36)
	at com.android.launcher3.anim.AnimatorPlaybackController.callListenerCommandRecursively(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:7)
	at com.android.launcher3.anim.AnimatorPlaybackController.dispatchOnEnd(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:9)
	at com.android.launcher3.anim.AnimatorPlaybackController$OnAnimationEndDispatcher.onAnimationSuccess(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:7)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(go/retraceme d64815e9bb1a1e22c3f9643b1a3046dfb4cece8716c9ab9e81a56f1b7725d51a:5)

Change-Id: I1177d10819843840d625caa93156f1ad86df5502
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
(cherry picked from commit 6185f7a99d300c4b8e395fb8f913a9646a4703a8)
Signed-off-by: Jis G Jacob <studiokeys@blissroms.org>